services:
  postgresql-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgresql-db:/var/lib/postgresql/data

  order-pack-calculator-api:
    build: .
    container_name: order-pack-calculator-api
    hostname: order-pack-calculator-api
    ports:
      - "8080:8080"
    depends_on:
      - postgresql-db
    environment:
      - PORT=8080
      - APP_ENV=${APP_ENV}
      - DB_HOST=postgresql-db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SCHEMA=${DB_SCHEMA}
volumes:
  postgresql-db:
    driver: local
